#pragma once
double const CONST_COINFLIP = 0.5;
double const CONST_GRANDE_MUTATION_PART = 0.2;
int const CONST_ITERATIONS_TO_BREAK_STUCK = 100;
int const CONST_NUMBER_OF_GENETIC_ALGORYTHMS = 20;
int const CONST_NUMBER_OF_ITERATIONS_TO_MIGRATE = 15;
